name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  MODRINTH_ID: 8gdV1Har
  CURSEFORGE_ID: 1260304

jobs:
  find_versions:
    runs-on: ubuntu-latest
    outputs:
      minecraftVersions: ${{ steps.find_versions.outputs.minecraftVersions }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: find versions
        id: find_versions
        run: |
          minecraftVersions=$(ls -1 versions | jq -R | jq -s -c)
          echo "minecraftVersions=${minecraftVersions}" >> "$GITHUB_OUTPUT"

  build:
    strategy:
      matrix:
        minecraftVersion: ${{ fromJson(needs.find_versions.outputs.minecraftVersions) }}
      fail-fast: false
    runs-on: ubuntu-latest
    needs: find_versions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Set Minecraft Version
        run: ./gradlew "Set active project to ${{ matrix.minecraftVersion }}"

      - name: Build
        run: ./gradlew clean build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WingedSandals-${{ matrix.minecraftVersion }}
          path: versions/${{ matrix.minecraftVersion }}/build/libs/

      - name: get changelog
        id: changelog
        run: |
          # Get the latest changelog from CHANGELOG.md
          {
            echo "changelog<<EOF"
            awk 'p && /^#/ { exit } p && NF { print } /^#/ { p=1 }' CHANGELOG.md
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: publish 1.20.x
        if: matrix.minecraftVersion == '1.20.1'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: WingedSandals ${{ github.ref_name }} for Minecraft 1.20.x
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            versions/${{ matrix.minecraftVersion }}/build/libs/*.jar
          game-versions: |
            >=1.20 <1.21
          java: |
            17
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: publish 1.21-1.21.1
        if: matrix.minecraftVersion == '1.21.1'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: WingedSandals ${{ github.ref_name }} for Minecraft 1.21-1.21.1
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            versions/${{ matrix.minecraftVersion }}/build/libs/*.jar
          game-versions: |
            >=1.21 <1.21.2
          java: |
            21
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: publish 1.21.2-1.21.3
        if: matrix.minecraftVersion == '1.21.2'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: WingedSandals ${{ github.ref_name }} for Minecraft 1.21.2-1.21.3
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            versions/${{ matrix.minecraftVersion }}/build/libs/*.jar
          game-versions: |
            >=1.21.2 <1.21.4
          java: |
            21
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: publish 1.21.4
        if: matrix.minecraftVersion == '1.21.4'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: WingedSandals ${{ github.ref_name }} for Minecraft 1.21.4
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            versions/${{ matrix.minecraftVersion }}/build/libs/*.jar
          game-versions: |
            >=1.21.4 <1.21.5
          java: |
            21
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: publish 1.21.5
        if: matrix.minecraftVersion == '1.21.5'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: WingedSandals ${{ github.ref_name }} for Minecraft 1.21.5
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            versions/${{ matrix.minecraftVersion }}/build/libs/*.jar
          game-versions: |
            >=1.21.5 <1.22
          java: |
            21
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
